### ISSUE TITLE
Search by user's url does not match with all cases

### ISSUE THREAD

**Issue by Huy-Ngo** [kaleidawave/reddit-karma#1]
The placeholder suggest that searching for `reddit.com/user/<username>` should match, but in reality, it only matches for `www.reddit.com/user/<username>` and `<username>`. Please handle all cases.

**Comment by kaleidawave** [comment]
Fixed in https://github.com/kaleidawave/reddit-karma/commit/48186301d8345f391f32528d628e979193235e3e thanks to your implmentation
